sss = "hello world in the worm !"
print('sss : ' + str(  sss  ) )

ttt = "hello\tworld\tin\tthe\tworm\t!"
print('ttt : ' + str(  ttt  ) )

rus = "Привет земля, Флэш Гордон приближается !"
print('rus : ' + str(  rus  ) )

bbb = "HELLO WORLD!"
print('bbb : ' + str(  bbb  ) )

print('------------------------')

print('sss.capitalize() : ' + str(  sss.capitalize()  ) )
print('bbb.casefold() : ' + str(  bbb.casefold()  ) )
print('sss.center(50,"-") : ' + str( '"'+ sss.center(50,'-') + '"' ) )
print('sss.count("wor") : ' + str(  sss.count("wor")  ) )
print('rus.encode("cp1251") : ' + str(  rus.encode('cp1251')  ) )
print('sss.endswith("m !") : ' + str(  sss.endswith("m !")  ) )
print('ttt.expandtabs() : ' + str(  ttt.expandtabs()  ) )
print('sss.find("wo") : ' + str(  sss.find("wo")  ) )
print('format: "sum of 1 and 2 is {}".format(1+2) : ' + str(  "sum of 1 and 2 is {}".format(1+2)  ) )
print('sss.index("wo") : ' + str(  sss.index("wo")  ) )
# здесь будет ошибка "ValueError: substring not found", т.к. такой подстроки нет
#print('sss.index("123") : ' + str(  sss.index("123")  ) )
print('sss.isalnum() : ' + str(  sss.isalnum()  ) )
print('"onlylettersanddigits222".isalnum() : ' + str(  "onlylettersanddigits222".isalnum()  ) )
print('sss.isalpha() : ' + str(  sss.isalpha()  ) )
print('"onlyletters".isalpha() : ' + str(  "onlyletters".isalpha()  ) )
print('sss.isascii() : ' + str(  sss.isascii()  ) )
print('sss.isdecimal() : ' + str(  sss.isdecimal()  ) )
print('"23456789".isdecimal() : ' + str(  "23456789".isdecimal()  ) )
print('sss.isdigit() : ' + str(  sss.isdigit()  ) )
print('"345678".isdigit() : ' + str(  "345678".isdigit()  ) )
print('sss.isidentifier() : ' + str(  sss.isidentifier()  ) )
print('"newIden".isidentifier() : ' + str(  "newIden".isidentifier()  ) )
print('sss.islower() : ' + str(  sss.islower()  ) )
print('sss.isnumeric() : ' + str(  sss.isnumeric()  ) )
print('"12222".isnumeric() : ' + str(  "12222".isnumeric()  ) )
print('sss.isprintable() : ' + str(  sss.isprintable()  ) )
print('sss.isspace() : ' + str(  sss.isspace()  ) )
print('"   ".isspace() : ' + str(  "   ".isspace()  ) )
print('sss.istitle() : ' + str(  sss.istitle()  ) )
print('"Welcome".istitle() : ' + str(  "Welcome".istitle()  ) )
print('sss.isupper() : ' + str(  sss.isupper()  ) )
print('bbb.isupper() : ' + str(  bbb.isupper()  ) )
print('sss.join("another string") : ' + str(  sss.join("another string")  ) )
print('sss.ljust(50) : ' + str( '"'+ sss.ljust(50) +'"' ) )
print('bbb.lower() : ' + str(  bbb.lower()  ) )
print('"    spaces on the left".lstrip() : ' + str( "'"+ "    spaces on the left".lstrip() +"'" ) )
print('"spaces on the right    ".rstrip() : ' + str( "'"+ "spaces on the right    ".rstrip() +"'" ) )
print('sss.partition(" ") : ' + str(  sss.partition(" ")  ) )
print('sss.replace("wo", "wonder") : ' + str(  sss.replace("wo", "wonder")  ) )
print('sss.rfind("wo") : ' + str(  sss.rfind("wo")  ) )
print('sss.rindex("wo") : ' + str(  sss.rindex("wo")  ) )
# здесь будет ошибка "ValueError: substring not found", т.к. такой подстроки нет
#print('sss.rindex("123") : ' + str(  sss.rindex("123")  ) )
print('sss.rpartition(" ") : ' + str(  sss.rpartition(" ")  ) )
print('sss.rsplit(" ") : ' + str(  sss.rsplit(" ")  ) )
print('sss.split(" ") : ' + str(  sss.split(" ")  ) )
print('"this\nis\ndivided\nline".splitlines() : ' + str(  "this\nis\ndivided\nline".splitlines() ) )
print('sss.startswith("hel") : ' + str(  sss.startswith("hel")  ) )
print('"    spaces on the both    ".strip() : ' + str( "'"+ "    spaces on the both    ".strip() +"'" ) )
print('"Hello".swapcase() : ' + str(  "Hello".swapcase()  ) )
print('sss.title() : ' + str(  sss.title()  ) )
print('sss.upper() : ' + str(  sss.upper()  ) )
print('sss.zfill(50) : ' + str(  sss.zfill(50)  ) )
